// Mocks generated by Mockito 5.3.0 from annotations
// in ditonton/test/helpers/test_helper.dart.
// Do not manually edit this file.

// ignore_for_file: no_leading_underscores_for_library_prefixes
import 'dart:async' as _i9;
import 'dart:convert' as _i27;
import 'dart:typed_data' as _i28;

import 'package:dartz/dartz.dart' as _i2;
import 'package:ditonton/common/failure.dart' as _i10;
import 'package:ditonton/data/datasources/db/database_helper.dart' as _i24;
import 'package:ditonton/data/datasources/movie_local_data_source.dart' as _i20;
import 'package:ditonton/data/datasources/movie_remote_data_source.dart'
    as _i16;
import 'package:ditonton/data/datasources/tv_series_local_data_source.dart'
    as _i22;
import 'package:ditonton/data/datasources/tv_series_remote_data_source.dart'
    as _i18;
import 'package:ditonton/data/models/movie_detail_model.dart' as _i3;
import 'package:ditonton/data/models/movie_model.dart' as _i17;
import 'package:ditonton/data/models/movie_table.dart' as _i21;
import 'package:ditonton/data/models/tv_series_detail_model.dart' as _i4;
import 'package:ditonton/data/models/tv_series_model.dart' as _i19;
import 'package:ditonton/data/models/tv_series_table.dart' as _i23;
import 'package:ditonton/domain/entities/movie.dart' as _i11;
import 'package:ditonton/domain/entities/movie_detail.dart' as _i12;
import 'package:ditonton/domain/entities/tv_series.dart' as _i14;
import 'package:ditonton/domain/entities/tv_series_detail.dart' as _i15;
import 'package:ditonton/domain/repositories/movie_repository.dart' as _i8;
import 'package:ditonton/domain/repositories/tv_series_repository.dart' as _i13;
import 'package:http/io_client.dart' as _i5;
import 'package:http/src/base_request.dart' as _i26;
import 'package:http/src/client.dart' as _i29;
import 'package:http/src/response.dart' as _i6;
import 'package:http/src/streamed_response.dart' as _i7;
import 'package:mockito/mockito.dart' as _i1;
import 'package:sqflite/sqflite.dart' as _i25;

// ignore_for_file: type=lint
// ignore_for_file: avoid_redundant_argument_values
// ignore_for_file: avoid_setters_without_getters
// ignore_for_file: comment_references
// ignore_for_file: implementation_imports
// ignore_for_file: invalid_use_of_visible_for_testing_member
// ignore_for_file: prefer_const_constructors
// ignore_for_file: unnecessary_parenthesis
// ignore_for_file: camel_case_types
// ignore_for_file: subtype_of_sealed_class

class _FakeEither_0<L, R> extends _i1.SmartFake implements _i2.Either<L, R> {
  _FakeEither_0(Object parent, Invocation parentInvocation)
      : super(parent, parentInvocation);
}

class _FakeMovieDetailResponse_1 extends _i1.SmartFake
    implements _i3.MovieDetailResponse {
  _FakeMovieDetailResponse_1(Object parent, Invocation parentInvocation)
      : super(parent, parentInvocation);
}

class _FakeTvSeriesDetailResponse_2 extends _i1.SmartFake
    implements _i4.TvSeriesDetailResponse {
  _FakeTvSeriesDetailResponse_2(Object parent, Invocation parentInvocation)
      : super(parent, parentInvocation);
}

class _FakeIOStreamedResponse_3 extends _i1.SmartFake
    implements _i5.IOStreamedResponse {
  _FakeIOStreamedResponse_3(Object parent, Invocation parentInvocation)
      : super(parent, parentInvocation);
}

class _FakeResponse_4 extends _i1.SmartFake implements _i6.Response {
  _FakeResponse_4(Object parent, Invocation parentInvocation)
      : super(parent, parentInvocation);
}

class _FakeStreamedResponse_5 extends _i1.SmartFake
    implements _i7.StreamedResponse {
  _FakeStreamedResponse_5(Object parent, Invocation parentInvocation)
      : super(parent, parentInvocation);
}

/// A class which mocks [MovieRepository].
///
/// See the documentation for Mockito's code generation for more information.
class MockMovieRepository extends _i1.Mock implements _i8.MovieRepository {
  MockMovieRepository() {
    _i1.throwOnMissingStub(this);
  }

  @override
  _i9.Future<_i2.Either<_i10.Failure, List<_i11.Movie>>>
      getNowPlayingMovies() => (super.noSuchMethod(
              Invocation.method(#getNowPlayingMovies, []),
              returnValue:
                  _i9.Future<_i2.Either<_i10.Failure, List<_i11.Movie>>>.value(
                      _FakeEither_0<_i10.Failure, List<_i11.Movie>>(
                          this, Invocation.method(#getNowPlayingMovies, []))))
          as _i9.Future<_i2.Either<_i10.Failure, List<_i11.Movie>>>);
  @override
  _i9.Future<_i2.Either<_i10.Failure, List<_i11.Movie>>> getPopularMovies() =>
      (super.noSuchMethod(Invocation.method(#getPopularMovies, []),
              returnValue:
                  _i9.Future<_i2.Either<_i10.Failure, List<_i11.Movie>>>.value(
                      _FakeEither_0<_i10.Failure, List<_i11.Movie>>(
                          this, Invocation.method(#getPopularMovies, []))))
          as _i9.Future<_i2.Either<_i10.Failure, List<_i11.Movie>>>);
  @override
  _i9.Future<_i2.Either<_i10.Failure, List<_i11.Movie>>> getTopRatedMovies() =>
      (super.noSuchMethod(Invocation.method(#getTopRatedMovies, []),
              returnValue:
                  _i9.Future<_i2.Either<_i10.Failure, List<_i11.Movie>>>.value(
                      _FakeEither_0<_i10.Failure, List<_i11.Movie>>(
                          this, Invocation.method(#getTopRatedMovies, []))))
          as _i9.Future<_i2.Either<_i10.Failure, List<_i11.Movie>>>);
  @override
  _i9.Future<_i2.Either<_i10.Failure, _i12.MovieDetail>> getMovieDetail(
          int? id) =>
      (super.noSuchMethod(Invocation.method(#getMovieDetail, [id]),
              returnValue:
                  _i9.Future<_i2.Either<_i10.Failure, _i12.MovieDetail>>.value(
                      _FakeEither_0<_i10.Failure, _i12.MovieDetail>(
                          this, Invocation.method(#getMovieDetail, [id]))))
          as _i9.Future<_i2.Either<_i10.Failure, _i12.MovieDetail>>);
  @override
  _i9.Future<_i2.Either<_i10.Failure, List<_i11.Movie>>>
      getMovieRecommendations(int? id) => (super.noSuchMethod(
              Invocation.method(#getMovieRecommendations, [id]),
              returnValue:
                  _i9.Future<_i2.Either<_i10.Failure, List<_i11.Movie>>>.value(
                      _FakeEither_0<_i10.Failure, List<_i11.Movie>>(this,
                          Invocation.method(#getMovieRecommendations, [id]))))
          as _i9.Future<_i2.Either<_i10.Failure, List<_i11.Movie>>>);
  @override
  _i9.Future<_i2.Either<_i10.Failure, List<_i11.Movie>>> searchMovies(
          String? query) =>
      (super.noSuchMethod(Invocation.method(#searchMovies, [query]),
              returnValue:
                  _i9.Future<_i2.Either<_i10.Failure, List<_i11.Movie>>>.value(
                      _FakeEither_0<_i10.Failure, List<_i11.Movie>>(
                          this, Invocation.method(#searchMovies, [query]))))
          as _i9.Future<_i2.Either<_i10.Failure, List<_i11.Movie>>>);
  @override
  _i9.Future<_i2.Either<_i10.Failure, String>> saveMoviesWatchlist(
          _i12.MovieDetail? movie) =>
      (super.noSuchMethod(Invocation.method(#saveMoviesWatchlist, [movie]),
              returnValue: _i9.Future<_i2.Either<_i10.Failure, String>>.value(
                  _FakeEither_0<_i10.Failure, String>(
                      this, Invocation.method(#saveMoviesWatchlist, [movie]))))
          as _i9.Future<_i2.Either<_i10.Failure, String>>);
  @override
  _i9.Future<_i2.Either<_i10.Failure, String>> removeMoviesWatchlist(
          _i12.MovieDetail? movie) =>
      (super.noSuchMethod(Invocation.method(#removeMoviesWatchlist, [movie]),
              returnValue: _i9.Future<_i2.Either<_i10.Failure, String>>.value(
                  _FakeEither_0<_i10.Failure, String>(this,
                      Invocation.method(#removeMoviesWatchlist, [movie]))))
          as _i9.Future<_i2.Either<_i10.Failure, String>>);
  @override
  _i9.Future<bool> isMoviesAddedToWatchlist(int? id) =>
      (super.noSuchMethod(Invocation.method(#isMoviesAddedToWatchlist, [id]),
          returnValue: _i9.Future<bool>.value(false)) as _i9.Future<bool>);
  @override
  _i9.Future<_i2.Either<_i10.Failure, List<_i11.Movie>>> getWatchlistMovies() =>
      (super.noSuchMethod(Invocation.method(#getWatchlistMovies, []),
              returnValue:
                  _i9.Future<_i2.Either<_i10.Failure, List<_i11.Movie>>>.value(
                      _FakeEither_0<_i10.Failure, List<_i11.Movie>>(
                          this, Invocation.method(#getWatchlistMovies, []))))
          as _i9.Future<_i2.Either<_i10.Failure, List<_i11.Movie>>>);
}

/// A class which mocks [TvSeriesRepository].
///
/// See the documentation for Mockito's code generation for more information.
class MockTvSeriesRepository extends _i1.Mock
    implements _i13.TvSeriesRepository {
  MockTvSeriesRepository() {
    _i1.throwOnMissingStub(this);
  }

  @override
  _i9.Future<_i2.Either<_i10.Failure, List<_i14.TvSeries>>>
      getNowPlayingTvSeries() => (super.noSuchMethod(
          Invocation.method(#getNowPlayingTvSeries, []),
          returnValue:
              _i9.Future<_i2.Either<_i10.Failure, List<_i14.TvSeries>>>.value(
                  _FakeEither_0<_i10.Failure, List<_i14.TvSeries>>(this,
                      Invocation.method(#getNowPlayingTvSeries, [])))) as _i9
          .Future<_i2.Either<_i10.Failure, List<_i14.TvSeries>>>);
  @override
  _i9.Future<_i2.Either<_i10.Failure, List<_i14.TvSeries>>>
      getPopularTvSeries() => (super.noSuchMethod(
          Invocation.method(#getPopularTvSeries, []),
          returnValue:
              _i9.Future<_i2.Either<_i10.Failure, List<_i14.TvSeries>>>.value(
                  _FakeEither_0<_i10.Failure, List<_i14.TvSeries>>(
                      this, Invocation.method(#getPopularTvSeries, [])))) as _i9
          .Future<_i2.Either<_i10.Failure, List<_i14.TvSeries>>>);
  @override
  _i9.Future<_i2.Either<_i10.Failure, List<_i14.TvSeries>>>
      getTopRatedTvSeries() => (super.noSuchMethod(
          Invocation.method(#getTopRatedTvSeries, []),
          returnValue:
              _i9.Future<_i2.Either<_i10.Failure, List<_i14.TvSeries>>>.value(
                  _FakeEither_0<_i10.Failure, List<_i14.TvSeries>>(this,
                      Invocation.method(#getTopRatedTvSeries, [])))) as _i9
          .Future<_i2.Either<_i10.Failure, List<_i14.TvSeries>>>);
  @override
  _i9.Future<_i2.Either<_i10.Failure, _i15.TvSeriesDetail>> getTvSeriesDetail(
          int? id) =>
      (super.noSuchMethod(Invocation.method(#getTvSeriesDetail, [id]),
          returnValue:
              _i9.Future<_i2.Either<_i10.Failure, _i15.TvSeriesDetail>>.value(
                  _FakeEither_0<_i10.Failure, _i15.TvSeriesDetail>(this,
                      Invocation.method(#getTvSeriesDetail, [id])))) as _i9
          .Future<_i2.Either<_i10.Failure, _i15.TvSeriesDetail>>);
  @override
  _i9.Future<_i2.Either<_i10.Failure, List<_i14.TvSeries>>>
      getTvSeriesRecommendations(int? id) => (super.noSuchMethod(
              Invocation.method(#getTvSeriesRecommendations, [id]),
              returnValue:
                  _i9.Future<_i2.Either<_i10.Failure, List<_i14.TvSeries>>>.value(
                      _FakeEither_0<_i10.Failure, List<_i14.TvSeries>>(this,
                          Invocation.method(#getTvSeriesRecommendations, [id]))))
          as _i9.Future<_i2.Either<_i10.Failure, List<_i14.TvSeries>>>);
  @override
  _i9.Future<_i2.Either<_i10.Failure, List<_i14.TvSeries>>> searchTvSeries(
          String? query) =>
      (super.noSuchMethod(Invocation.method(#searchTvSeries, [query]),
          returnValue:
              _i9.Future<_i2.Either<_i10.Failure, List<_i14.TvSeries>>>.value(
                  _FakeEither_0<_i10.Failure, List<_i14.TvSeries>>(this,
                      Invocation.method(#searchTvSeries, [query])))) as _i9
          .Future<_i2.Either<_i10.Failure, List<_i14.TvSeries>>>);
  @override
  _i9.Future<_i2.Either<_i10.Failure, String>> saveTvSeriesWatchlist(
          _i15.TvSeriesDetail? tvSeries) =>
      (super.noSuchMethod(Invocation.method(#saveTvSeriesWatchlist, [tvSeries]),
              returnValue: _i9.Future<_i2.Either<_i10.Failure, String>>.value(
                  _FakeEither_0<_i10.Failure, String>(this,
                      Invocation.method(#saveTvSeriesWatchlist, [tvSeries]))))
          as _i9.Future<_i2.Either<_i10.Failure, String>>);
  @override
  _i9.Future<_i2.Either<_i10.Failure, String>> removeTvSeriesWatchlist(
          _i15.TvSeriesDetail? tvSeries) =>
      (super.noSuchMethod(
              Invocation.method(#removeTvSeriesWatchlist, [tvSeries]),
              returnValue: _i9.Future<_i2.Either<_i10.Failure, String>>.value(
                  _FakeEither_0<_i10.Failure, String>(this,
                      Invocation.method(#removeTvSeriesWatchlist, [tvSeries]))))
          as _i9.Future<_i2.Either<_i10.Failure, String>>);
  @override
  _i9.Future<bool> isTvSeriesAddedToWatchlist(int? id) =>
      (super.noSuchMethod(Invocation.method(#isTvSeriesAddedToWatchlist, [id]),
          returnValue: _i9.Future<bool>.value(false)) as _i9.Future<bool>);
  @override
  _i9.Future<_i2.Either<_i10.Failure, List<_i14.TvSeries>>>
      getWatchlistTvSeries() => (super.noSuchMethod(
          Invocation.method(#getWatchlistTvSeries, []),
          returnValue:
              _i9.Future<_i2.Either<_i10.Failure, List<_i14.TvSeries>>>.value(
                  _FakeEither_0<_i10.Failure, List<_i14.TvSeries>>(this,
                      Invocation.method(#getWatchlistTvSeries, [])))) as _i9
          .Future<_i2.Either<_i10.Failure, List<_i14.TvSeries>>>);
}

/// A class which mocks [MovieRemoteDataSource].
///
/// See the documentation for Mockito's code generation for more information.
class MockMovieRemoteDataSource extends _i1.Mock
    implements _i16.MovieRemoteDataSource {
  MockMovieRemoteDataSource() {
    _i1.throwOnMissingStub(this);
  }

  @override
  _i9.Future<List<_i17.MovieModel>> getNowPlayingMovies() =>
      (super.noSuchMethod(Invocation.method(#getNowPlayingMovies, []),
              returnValue:
                  _i9.Future<List<_i17.MovieModel>>.value(<_i17.MovieModel>[]))
          as _i9.Future<List<_i17.MovieModel>>);
  @override
  _i9.Future<List<_i17.MovieModel>> getPopularMovies() =>
      (super.noSuchMethod(Invocation.method(#getPopularMovies, []),
              returnValue:
                  _i9.Future<List<_i17.MovieModel>>.value(<_i17.MovieModel>[]))
          as _i9.Future<List<_i17.MovieModel>>);
  @override
  _i9.Future<List<_i17.MovieModel>> getTopRatedMovies() =>
      (super.noSuchMethod(Invocation.method(#getTopRatedMovies, []),
              returnValue:
                  _i9.Future<List<_i17.MovieModel>>.value(<_i17.MovieModel>[]))
          as _i9.Future<List<_i17.MovieModel>>);
  @override
  _i9.Future<_i3.MovieDetailResponse> getMovieDetail(int? id) =>
      (super.noSuchMethod(Invocation.method(#getMovieDetail, [id]),
              returnValue: _i9.Future<_i3.MovieDetailResponse>.value(
                  _FakeMovieDetailResponse_1(
                      this, Invocation.method(#getMovieDetail, [id]))))
          as _i9.Future<_i3.MovieDetailResponse>);
  @override
  _i9.Future<List<_i17.MovieModel>> getMovieRecommendations(int? id) =>
      (super.noSuchMethod(Invocation.method(#getMovieRecommendations, [id]),
              returnValue:
                  _i9.Future<List<_i17.MovieModel>>.value(<_i17.MovieModel>[]))
          as _i9.Future<List<_i17.MovieModel>>);
  @override
  _i9.Future<List<_i17.MovieModel>> searchMovies(String? query) =>
      (super.noSuchMethod(Invocation.method(#searchMovies, [query]),
              returnValue:
                  _i9.Future<List<_i17.MovieModel>>.value(<_i17.MovieModel>[]))
          as _i9.Future<List<_i17.MovieModel>>);
}

/// A class which mocks [TvSeriesRemoteDataSource].
///
/// See the documentation for Mockito's code generation for more information.
class MockTvSeriesRemoteDataSource extends _i1.Mock
    implements _i18.TvSeriesRemoteDataSource {
  MockTvSeriesRemoteDataSource() {
    _i1.throwOnMissingStub(this);
  }

  @override
  _i9.Future<List<_i19.TvSeriesModel>> getNowPlayingTvSeries() =>
      (super.noSuchMethod(Invocation.method(#getNowPlayingTvSeries, []),
          returnValue: _i9.Future<List<_i19.TvSeriesModel>>.value(
              <_i19.TvSeriesModel>[])) as _i9.Future<List<_i19.TvSeriesModel>>);
  @override
  _i9.Future<List<_i19.TvSeriesModel>> getPopularTvSeries() =>
      (super.noSuchMethod(Invocation.method(#getPopularTvSeries, []),
          returnValue: _i9.Future<List<_i19.TvSeriesModel>>.value(
              <_i19.TvSeriesModel>[])) as _i9.Future<List<_i19.TvSeriesModel>>);
  @override
  _i9.Future<List<_i19.TvSeriesModel>> getTopRatedTvSeries() =>
      (super.noSuchMethod(Invocation.method(#getTopRatedTvSeries, []),
          returnValue: _i9.Future<List<_i19.TvSeriesModel>>.value(
              <_i19.TvSeriesModel>[])) as _i9.Future<List<_i19.TvSeriesModel>>);
  @override
  _i9.Future<_i4.TvSeriesDetailResponse> getTvSeriesDetail(int? id) =>
      (super.noSuchMethod(Invocation.method(#getTvSeriesDetail, [id]),
              returnValue: _i9.Future<_i4.TvSeriesDetailResponse>.value(
                  _FakeTvSeriesDetailResponse_2(
                      this, Invocation.method(#getTvSeriesDetail, [id]))))
          as _i9.Future<_i4.TvSeriesDetailResponse>);
  @override
  _i9.Future<List<_i19.TvSeriesModel>> getTvSeriesRecommendations(int? id) =>
      (super.noSuchMethod(Invocation.method(#getTvSeriesRecommendations, [id]),
          returnValue: _i9.Future<List<_i19.TvSeriesModel>>.value(
              <_i19.TvSeriesModel>[])) as _i9.Future<List<_i19.TvSeriesModel>>);
  @override
  _i9.Future<List<_i19.TvSeriesModel>> searchTvSeries(String? query) =>
      (super.noSuchMethod(Invocation.method(#searchTvSeries, [query]),
          returnValue: _i9.Future<List<_i19.TvSeriesModel>>.value(
              <_i19.TvSeriesModel>[])) as _i9.Future<List<_i19.TvSeriesModel>>);
}

/// A class which mocks [MovieLocalDataSource].
///
/// See the documentation for Mockito's code generation for more information.
class MockMovieLocalDataSource extends _i1.Mock
    implements _i20.MovieLocalDataSource {
  MockMovieLocalDataSource() {
    _i1.throwOnMissingStub(this);
  }

  @override
  _i9.Future<String> insertWatchlist(_i21.MovieTable? movie) =>
      (super.noSuchMethod(Invocation.method(#insertWatchlist, [movie]),
          returnValue: _i9.Future<String>.value('')) as _i9.Future<String>);
  @override
  _i9.Future<String> removeWatchlist(_i21.MovieTable? movie) =>
      (super.noSuchMethod(Invocation.method(#removeWatchlist, [movie]),
          returnValue: _i9.Future<String>.value('')) as _i9.Future<String>);
  @override
  _i9.Future<_i21.MovieTable?> getMovieById(int? id) =>
      (super.noSuchMethod(Invocation.method(#getMovieById, [id]),
              returnValue: _i9.Future<_i21.MovieTable?>.value())
          as _i9.Future<_i21.MovieTable?>);
  @override
  _i9.Future<List<_i21.MovieTable>> getMovieWatchlist() =>
      (super.noSuchMethod(Invocation.method(#getMovieWatchlist, []),
              returnValue:
                  _i9.Future<List<_i21.MovieTable>>.value(<_i21.MovieTable>[]))
          as _i9.Future<List<_i21.MovieTable>>);
}

/// A class which mocks [TvSeriesLocalDataSource].
///
/// See the documentation for Mockito's code generation for more information.
class MockTvSeriesLocalDataSource extends _i1.Mock
    implements _i22.TvSeriesLocalDataSource {
  MockTvSeriesLocalDataSource() {
    _i1.throwOnMissingStub(this);
  }

  @override
  _i9.Future<String> insertWatchList(_i23.TvSeriesTable? tvSeries) =>
      (super.noSuchMethod(Invocation.method(#insertWatchList, [tvSeries]),
          returnValue: _i9.Future<String>.value('')) as _i9.Future<String>);
  @override
  _i9.Future<String> removeWatchList(_i23.TvSeriesTable? tvSeries) =>
      (super.noSuchMethod(Invocation.method(#removeWatchList, [tvSeries]),
          returnValue: _i9.Future<String>.value('')) as _i9.Future<String>);
  @override
  _i9.Future<_i23.TvSeriesTable?> getTvSeriesId(int? id) =>
      (super.noSuchMethod(Invocation.method(#getTvSeriesId, [id]),
              returnValue: _i9.Future<_i23.TvSeriesTable?>.value())
          as _i9.Future<_i23.TvSeriesTable?>);
  @override
  _i9.Future<List<_i23.TvSeriesTable>> getTvSeriesWatchlist() =>
      (super.noSuchMethod(Invocation.method(#getTvSeriesWatchlist, []),
          returnValue: _i9.Future<List<_i23.TvSeriesTable>>.value(
              <_i23.TvSeriesTable>[])) as _i9.Future<List<_i23.TvSeriesTable>>);
}

/// A class which mocks [DatabaseHelper].
///
/// See the documentation for Mockito's code generation for more information.
class MockDatabaseHelper extends _i1.Mock implements _i24.DatabaseHelper {
  MockDatabaseHelper() {
    _i1.throwOnMissingStub(this);
  }

  @override
  set setTestDatabase(_i25.Database? db) =>
      super.noSuchMethod(Invocation.setter(#setTestDatabase, db),
          returnValueForMissingStub: null);
  @override
  _i9.Future<_i25.Database?> get database =>
      (super.noSuchMethod(Invocation.getter(#database),
              returnValue: _i9.Future<_i25.Database?>.value())
          as _i9.Future<_i25.Database?>);
  @override
  _i9.Future<int> insertMovieWatchlist(_i21.MovieTable? movie) =>
      (super.noSuchMethod(Invocation.method(#insertMovieWatchlist, [movie]),
          returnValue: _i9.Future<int>.value(0)) as _i9.Future<int>);
  @override
  _i9.Future<int> insertTvSeriesWatchlist(_i23.TvSeriesTable? tvSeries) =>
      (super.noSuchMethod(
          Invocation.method(#insertTvSeriesWatchlist, [tvSeries]),
          returnValue: _i9.Future<int>.value(0)) as _i9.Future<int>);
  @override
  _i9.Future<int> removeMovieWatchlist(_i21.MovieTable? movie) =>
      (super.noSuchMethod(Invocation.method(#removeMovieWatchlist, [movie]),
          returnValue: _i9.Future<int>.value(0)) as _i9.Future<int>);
  @override
  _i9.Future<int> removeTvSeriesWatchlist(_i23.TvSeriesTable? tvSeries) =>
      (super.noSuchMethod(
          Invocation.method(#removeTvSeriesWatchlist, [tvSeries]),
          returnValue: _i9.Future<int>.value(0)) as _i9.Future<int>);
  @override
  _i9.Future<Map<String, dynamic>?> getContentById(int? id) =>
      (super.noSuchMethod(Invocation.method(#getContentById, [id]),
              returnValue: _i9.Future<Map<String, dynamic>?>.value())
          as _i9.Future<Map<String, dynamic>?>);
  @override
  _i9.Future<List<Map<String, dynamic>>> getMovieWatchlist() =>
      (super.noSuchMethod(Invocation.method(#getMovieWatchlist, []),
              returnValue: _i9.Future<List<Map<String, dynamic>>>.value(
                  <Map<String, dynamic>>[]))
          as _i9.Future<List<Map<String, dynamic>>>);
  @override
  _i9.Future<List<Map<String, dynamic>>> getTvSeriesWatchlist() =>
      (super.noSuchMethod(Invocation.method(#getTvSeriesWatchlist, []),
              returnValue: _i9.Future<List<Map<String, dynamic>>>.value(
                  <Map<String, dynamic>>[]))
          as _i9.Future<List<Map<String, dynamic>>>);
}

/// A class which mocks [IOClient].
///
/// See the documentation for Mockito's code generation for more information.
class MockIOClient extends _i1.Mock implements _i5.IOClient {
  MockIOClient() {
    _i1.throwOnMissingStub(this);
  }

  @override
  _i9.Future<_i5.IOStreamedResponse> send(_i26.BaseRequest? request) =>
      (super.noSuchMethod(Invocation.method(#send, [request]),
              returnValue: _i9.Future<_i5.IOStreamedResponse>.value(
                  _FakeIOStreamedResponse_3(
                      this, Invocation.method(#send, [request]))))
          as _i9.Future<_i5.IOStreamedResponse>);
  @override
  void close() => super.noSuchMethod(Invocation.method(#close, []),
      returnValueForMissingStub: null);
  @override
  _i9.Future<_i6.Response> head(Uri? url, {Map<String, String>? headers}) =>
      (super.noSuchMethod(Invocation.method(#head, [url], {#headers: headers}),
              returnValue: _i9.Future<_i6.Response>.value(_FakeResponse_4(
                  this, Invocation.method(#head, [url], {#headers: headers}))))
          as _i9.Future<_i6.Response>);
  @override
  _i9.Future<_i6.Response> get(Uri? url, {Map<String, String>? headers}) =>
      (super.noSuchMethod(Invocation.method(#get, [url], {#headers: headers}),
              returnValue: _i9.Future<_i6.Response>.value(_FakeResponse_4(
                  this, Invocation.method(#get, [url], {#headers: headers}))))
          as _i9.Future<_i6.Response>);
  @override
  _i9.Future<_i6.Response> post(Uri? url,
          {Map<String, String>? headers,
          Object? body,
          _i27.Encoding? encoding}) =>
      (super
          .noSuchMethod(Invocation.method(#post, [url], {#headers: headers, #body: body, #encoding: encoding}),
              returnValue: _i9.Future<_i6.Response>.value(_FakeResponse_4(
                  this,
                  Invocation.method(#post, [
                    url
                  ], {
                    #headers: headers,
                    #body: body,
                    #encoding: encoding
                  })))) as _i9.Future<_i6.Response>);
  @override
  _i9.Future<_i6.Response> put(Uri? url,
          {Map<String, String>? headers,
          Object? body,
          _i27.Encoding? encoding}) =>
      (super
          .noSuchMethod(Invocation.method(#put, [url], {#headers: headers, #body: body, #encoding: encoding}),
              returnValue: _i9.Future<_i6.Response>.value(_FakeResponse_4(
                  this,
                  Invocation.method(#put, [
                    url
                  ], {
                    #headers: headers,
                    #body: body,
                    #encoding: encoding
                  })))) as _i9.Future<_i6.Response>);
  @override
  _i9.Future<_i6.Response> patch(Uri? url,
          {Map<String, String>? headers,
          Object? body,
          _i27.Encoding? encoding}) =>
      (super
          .noSuchMethod(Invocation.method(#patch, [url], {#headers: headers, #body: body, #encoding: encoding}),
              returnValue: _i9.Future<_i6.Response>.value(_FakeResponse_4(
                  this,
                  Invocation.method(#patch, [
                    url
                  ], {
                    #headers: headers,
                    #body: body,
                    #encoding: encoding
                  })))) as _i9.Future<_i6.Response>);
  @override
  _i9.Future<_i6.Response> delete(Uri? url,
          {Map<String, String>? headers,
          Object? body,
          _i27.Encoding? encoding}) =>
      (super
          .noSuchMethod(Invocation.method(#delete, [url], {#headers: headers, #body: body, #encoding: encoding}),
              returnValue: _i9.Future<_i6.Response>.value(_FakeResponse_4(
                  this,
                  Invocation.method(#delete, [
                    url
                  ], {
                    #headers: headers,
                    #body: body,
                    #encoding: encoding
                  })))) as _i9.Future<_i6.Response>);
  @override
  _i9.Future<String> read(Uri? url, {Map<String, String>? headers}) =>
      (super.noSuchMethod(Invocation.method(#read, [url], {#headers: headers}),
          returnValue: _i9.Future<String>.value('')) as _i9.Future<String>);
  @override
  _i9.Future<_i28.Uint8List> readBytes(Uri? url,
          {Map<String, String>? headers}) =>
      (super.noSuchMethod(
              Invocation.method(#readBytes, [url], {#headers: headers}),
              returnValue: _i9.Future<_i28.Uint8List>.value(_i28.Uint8List(0)))
          as _i9.Future<_i28.Uint8List>);
}

/// A class which mocks [Client].
///
/// See the documentation for Mockito's code generation for more information.
class MockHttpClient extends _i1.Mock implements _i29.Client {
  MockHttpClient() {
    _i1.throwOnMissingStub(this);
  }

  @override
  _i9.Future<_i6.Response> head(Uri? url, {Map<String, String>? headers}) =>
      (super.noSuchMethod(Invocation.method(#head, [url], {#headers: headers}),
              returnValue: _i9.Future<_i6.Response>.value(_FakeResponse_4(
                  this, Invocation.method(#head, [url], {#headers: headers}))))
          as _i9.Future<_i6.Response>);
  @override
  _i9.Future<_i6.Response> get(Uri? url, {Map<String, String>? headers}) =>
      (super.noSuchMethod(Invocation.method(#get, [url], {#headers: headers}),
              returnValue: _i9.Future<_i6.Response>.value(_FakeResponse_4(
                  this, Invocation.method(#get, [url], {#headers: headers}))))
          as _i9.Future<_i6.Response>);
  @override
  _i9.Future<_i6.Response> post(Uri? url,
          {Map<String, String>? headers,
          Object? body,
          _i27.Encoding? encoding}) =>
      (super
          .noSuchMethod(Invocation.method(#post, [url], {#headers: headers, #body: body, #encoding: encoding}),
              returnValue: _i9.Future<_i6.Response>.value(_FakeResponse_4(
                  this,
                  Invocation.method(#post, [
                    url
                  ], {
                    #headers: headers,
                    #body: body,
                    #encoding: encoding
                  })))) as _i9.Future<_i6.Response>);
  @override
  _i9.Future<_i6.Response> put(Uri? url,
          {Map<String, String>? headers,
          Object? body,
          _i27.Encoding? encoding}) =>
      (super
          .noSuchMethod(Invocation.method(#put, [url], {#headers: headers, #body: body, #encoding: encoding}),
              returnValue: _i9.Future<_i6.Response>.value(_FakeResponse_4(
                  this,
                  Invocation.method(#put, [
                    url
                  ], {
                    #headers: headers,
                    #body: body,
                    #encoding: encoding
                  })))) as _i9.Future<_i6.Response>);
  @override
  _i9.Future<_i6.Response> patch(Uri? url,
          {Map<String, String>? headers,
          Object? body,
          _i27.Encoding? encoding}) =>
      (super
          .noSuchMethod(Invocation.method(#patch, [url], {#headers: headers, #body: body, #encoding: encoding}),
              returnValue: _i9.Future<_i6.Response>.value(_FakeResponse_4(
                  this,
                  Invocation.method(#patch, [
                    url
                  ], {
                    #headers: headers,
                    #body: body,
                    #encoding: encoding
                  })))) as _i9.Future<_i6.Response>);
  @override
  _i9.Future<_i6.Response> delete(Uri? url,
          {Map<String, String>? headers,
          Object? body,
          _i27.Encoding? encoding}) =>
      (super
          .noSuchMethod(Invocation.method(#delete, [url], {#headers: headers, #body: body, #encoding: encoding}),
              returnValue: _i9.Future<_i6.Response>.value(_FakeResponse_4(
                  this,
                  Invocation.method(#delete, [
                    url
                  ], {
                    #headers: headers,
                    #body: body,
                    #encoding: encoding
                  })))) as _i9.Future<_i6.Response>);
  @override
  _i9.Future<String> read(Uri? url, {Map<String, String>? headers}) =>
      (super.noSuchMethod(Invocation.method(#read, [url], {#headers: headers}),
          returnValue: _i9.Future<String>.value('')) as _i9.Future<String>);
  @override
  _i9.Future<_i28.Uint8List> readBytes(Uri? url,
          {Map<String, String>? headers}) =>
      (super.noSuchMethod(
              Invocation.method(#readBytes, [url], {#headers: headers}),
              returnValue: _i9.Future<_i28.Uint8List>.value(_i28.Uint8List(0)))
          as _i9.Future<_i28.Uint8List>);
  @override
  _i9.Future<_i7.StreamedResponse> send(_i26.BaseRequest? request) =>
      (super.noSuchMethod(Invocation.method(#send, [request]),
              returnValue: _i9.Future<_i7.StreamedResponse>.value(
                  _FakeStreamedResponse_5(
                      this, Invocation.method(#send, [request]))))
          as _i9.Future<_i7.StreamedResponse>);
  @override
  void close() => super.noSuchMethod(Invocation.method(#close, []),
      returnValueForMissingStub: null);
}
